"""Task and role schemas."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AliasChoices, BaseModel, BeforeValidator, ConfigDict, Field, field_validator


def _strip_string(value: object) -> object:
    if isinstance(value, str):
        return value.strip()
    return value


def _normalize_text_list(value: object) -> object:
    if value is None:
        return []
    if isinstance(value, str):
        stripped = value.strip()
        return [stripped] if stripped else []
    if isinstance(value, list):
        normalized: list[object] = []
        for item in value:
            if isinstance(item, str):
                stripped = item.strip()
                if stripped:
                    normalized.append(stripped)
                continue
            normalized.append(item)
        return normalized
    return value


RequiredText = Annotated[str, BeforeValidator(_strip_string), Field(min_length=1)]
Text = Annotated[str, BeforeValidator(_strip_string)]


class AgentRole(StrEnum):
    """Fixed agent roles. Model assignments remain replaceable."""

    MASTER = "master"
    PLANNER = "planner"
    ARCHITECT = "architect"
    FRONTEND = "frontend"
    BACKEND = "backend"
    DATABASE = "database"
    ROUTING = "routing"
    INTEGRATION = "integration"
    QA = "qa"


class TaskStatus(StrEnum):
    """Task lifecycle states."""

    PENDING = "pending"
    READY = "ready"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    COMPLETED = "completed"


class TaskPriority(StrEnum):
    """Planner task priority levels."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class TaskAssignedAgent(StrEnum):
    """Future worker-agent assignments produced by the planner."""

    FRONTEND = "frontend"
    BACKEND = "backend"
    DATABASE = "database"
    ROUTING = "routing"
    INTEGRATION = "integration"
    QA = "qa"


class TaskDefinition(BaseModel):
    """Executable work unit generated by the planner."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: RequiredText
    title: RequiredText
    description: Text = ""
    assigned_agent: TaskAssignedAgent = Field(
        validation_alias=AliasChoices("assigned_agent", "agent"),
    )
    priority: TaskPriority = TaskPriority.MEDIUM
    status: TaskStatus = TaskStatus.PENDING
    dependencies: list[str] = Field(default_factory=list)
    blueprint_reference: RequiredText

    @field_validator("dependencies", mode="before")
    @classmethod
    def normalize_dependencies(cls, value: object) -> object:
        """Normalize compact dependency output into a clean ID list."""

        return _normalize_text_list(value)

    @property
    def agent(self) -> TaskAssignedAgent:
        """Backward-compatible alias for earlier blueprint task entries."""

        return self.assigned_agent


class TaskPlan(BaseModel):
    """Persisted Phase 4 task plan."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = "4.0"
    tasks: list[TaskDefinition] = Field(default_factory=list)
