"""Task and role schemas."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class AgentRole(StrEnum):
    """Fixed agent roles. Model assignments remain replaceable."""

    MASTER = "master"
    PLANNER = "planner"
    ARCHITECT = "architect"
    FRONTEND = "frontend"
    BACKEND = "backend"
    DATABASE = "database"
    ROUTING = "routing"
    INTEGRATION = "integration"
    QA = "qa"


class TaskStatus(StrEnum):
    """Task lifecycle states."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class TaskDefinition(BaseModel):
    """Executable task generated by the future planner."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1)
    title: str = Field(min_length=1)
    agent: AgentRole
    description: str = ""
    status: TaskStatus = TaskStatus.PENDING
